# This file was generated by GoReleaser. DO NOT EDIT.
cask "branch" do
  name "branch"
  desc "A CLI tool for creating git branches with consistent naming patterns"
  homepage "https://github.com/owenrumney/branch"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "branch"

  on_macos do
    on_intel do
      url "https://github.com/owenrumney/branch/releases/download/v#{version}/branch_Darwin_x86_64.tar.gz"
      sha256 "a00f6849747d3206d9e006121981c2d01c7425ef9bf09a83a19f449cb390c80d"
    end
    on_arm do
      url "https://github.com/owenrumney/branch/releases/download/v#{version}/branch_Darwin_arm64.tar.gz"
      sha256 "a880971d3d2c711fe4bdbf683153bc30fcc4e95c838dfe6f957552a0aec54281"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/owenrumney/branch/releases/download/v#{version}/branch_Linux_x86_64.tar.gz"
      sha256 "751ce16a28016a4a2daf2b5e6c02e5a1d6a3d24d002aa614a170b001914cbd3d"
    end
    on_arm do
      url "https://github.com/owenrumney/branch/releases/download/v#{version}/branch_Linux_arm64.tar.gz"
      sha256 "51ec420f706e6e1991aba6daee8fc99f09334d944097fcbd65d5bb20a4da4ff5"
    end
  end

  # No zap stanza required
end
