# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazytrivy" do
  version "1.3.3"

  on_macos do
    on_intel do
      sha256 "c586b9a862423e5dbdb81e5a3b341727097d9e2a13fc2892bdd35cb9cf90e30d"
      url "https://github.com/owenrumney/lazytrivy/releases/download/v#{version}/lazytrivy-darwin-amd64"
      binary "lazytrivy-darwin-amd64", target: "lazytrivy"
    end
    on_arm do
      sha256 "8a66f82eb6d88c32f6b7ad4484c6a5ccb58b60925954c8ffac07c6a17d5f058d"
      url "https://github.com/owenrumney/lazytrivy/releases/download/v#{version}/lazytrivy-darwin-arm64"
      binary "lazytrivy-darwin-arm64", target: "lazytrivy"
    end
  end

  on_linux do
    on_intel do
      sha256 "2fec2afd9aeb24e1e4f29f30ed180483ca03fab6fded1d71ffa397ee534074b5"
      url "https://github.com/owenrumney/lazytrivy/releases/download/v#{version}/lazytrivy-linux-amd64"
      binary "lazytrivy-linux-amd64", target: "lazytrivy"
    end
    on_arm do
      sha256 "fec4c348c92b59f61a70e21b8e705fcac31e270f56cb52bb69e8786b1965b515"
      url "https://github.com/owenrumney/lazytrivy/releases/download/v#{version}/lazytrivy-linux-arm64"
      binary "lazytrivy-linux-arm64", target: "lazytrivy"
    end
  end

  name "lazytrivy"
  desc "A simple CLI tool to run Trivy scans interactively with sensible defaults."
  homepage "https://github.com/owenrumney/lazytrivy"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    # Remove quarantine attribute to avoid Gatekeeper issues
    system_command "/usr/bin/xattr",
                   args: ["-cr", staged_path.to_s],
                   sudo: false
  end

  # No zap stanza required

end
