# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazytrivy" do
  version "1.4.1"

  on_macos do
    on_intel do
      sha256 "0e43a45cdc7c7f0895f34287387fc2a75d98d8c15bad35097f4daa58bff414fa"
      url "https://github.com/owenrumney/lazytrivy/releases/download/v#{version}/lazytrivy-darwin-amd64"
      binary "lazytrivy-darwin-amd64", target: "lazytrivy"
    end
    on_arm do
      sha256 "455b4914f546127248539289386cb30ce93be330c16178c3faa1180101faf48f"
      url "https://github.com/owenrumney/lazytrivy/releases/download/v#{version}/lazytrivy-darwin-arm64"
      binary "lazytrivy-darwin-arm64", target: "lazytrivy"
    end
  end

  on_linux do
    on_intel do
      sha256 "06850f47ea357d03db3b4b635c2091f530664688339791197bd3b704ffefe15b"
      url "https://github.com/owenrumney/lazytrivy/releases/download/v#{version}/lazytrivy-linux-amd64"
      binary "lazytrivy-linux-amd64", target: "lazytrivy"
    end
    on_arm do
      sha256 "abd3110dfa1b01058ca69a398a467e0f4571ff1d38b0275ecc2575d306dd5ac9"
      url "https://github.com/owenrumney/lazytrivy/releases/download/v#{version}/lazytrivy-linux-arm64"
      binary "lazytrivy-linux-arm64", target: "lazytrivy"
    end
  end

  name "lazytrivy"
  desc "A simple CLI tool to run Trivy scans interactively with sensible defaults."
  homepage "https://github.com/owenrumney/lazytrivy"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    # Remove quarantine attribute to avoid Gatekeeper issues
    system_command "/usr/bin/xattr",
                   args: ["-cr", staged_path.to_s],
                   sudo: false
  end

  # No zap stanza required

end
