# This file was generated by GoReleaser. DO NOT EDIT.
cask "schnappit" do
  name "schnappit"
  desc "A macOS screenshot utility"
  homepage "https://github.com/owenrumney/schnappit"
  version "0.1.5"

  url "https://github.com/owenrumney/schnappit/releases/download/v#{version}/Schnappit_#{version}_macOS.dmg"
  sha256 "a27f7ea9745c1c1b13b38af867030ab07ddfd5580e9b2fb6a3f0a8742ef5ad75" 

  livecheck do
    skip "Auto-generated on release."
  end

  app "Schnappit.app"

  preflight do
    # Remove quarantine attribute to avoid Gatekeeper issues
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{staged_path}/Schnappit.app"],
                   sudo: false
  end

  # No zap stanza required
end
