# This file was generated by GoReleaser. DO NOT EDIT.
cask "schnappit" do
  name "schnappit"
  desc "A macOS screenshot utility"
  homepage "https://github.com/owenrumney/schnappit"
  version "0.1.6"

  url "https://github.com/owenrumney/schnappit/releases/download/v#{version}/Schnappit_#{version}_macOS.dmg"
  sha256 "7fa9fa2a435b3cb0eab8eb83e19a97c359444a56687b58ea19efd7e8768a4367" 

  livecheck do
    skip "Auto-generated on release."
  end

  app "Schnappit.app"

  preflight do
    # Remove quarantine attribute to avoid Gatekeeper issues
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{staged_path}/Schnappit.app"],
                   sudo: false
  end

  # No zap stanza required
end
